-- Fix "null value in column id of relation wineries violates not-null constraint"
-- when creating a winery (lib/wineries.js createWinery inserts without an id).
--
-- wineries.id is a bigint PK that was NEVER given an auto-increment default — the
-- 306 seed rows (ids 1..305) were imported with explicit ids, so the column has no
-- sequence/identity. App inserts omit id → null → NOT NULL violation.
--
-- Convert id to GENERATED BY DEFAULT AS IDENTITY (BY DEFAULT, not ALWAYS, so future
-- seed imports can still supply explicit ids), then advance the new sequence past the
-- current max so generated ids don't collide. Idempotent guard on is_identity.

do $$
begin
  if (select is_identity from information_schema.columns
        where table_schema='public' and table_name='wineries' and column_name='id') = 'NO' then
    alter table public.wineries alter column id add generated by default as identity;
  end if;
end $$;

-- Advance the identity sequence to max(id) so the next generated id is max+1.
select setval(pg_get_serial_sequence('public.wineries','id'),
              coalesce((select max(id) from public.wineries), 0));
